# Site Settings
title: Sanjeev Kumar
url: 'http://sanjusci.github.io'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Sanjeev Kumar
tagline: Software Engineer
subtagline: (Python|JAVA|PHP)
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '
<p>Over 10+ years of experience in Software engineering and Data engineering professional with extensive experience 
in developing scalable data solutions and managing complex software projects. Reliable in driving results with key 
skills in data modeling, ETL processes, and cloud-based data platforms. Known for strong commitment to team 
collaboration and delivering high-quality results. Recognized for problem-solving abilities and adaptability in 
dynamic environments, with advanced skills in programming, system architecture, and team leadership.</p>
'

#sidebar links
email: sanjeev.notification@gmail.com
phone: +91-9650318107
#website: blog.sanjusci.com #do not add http://
linkedin: sanjusci
github: sanjusci
#twitter: ''
#Update all the sections by editing the files inside _data folder.

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
